//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Production = new HashSet<Production>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Article { get; set; }
        public Nullable<float> Min_cost_from_agent { get; set; }
        public string Image { get; set; }
        public Nullable<int> Id_Type_product { get; set; }
        public Nullable<int> Count_Person { get; set; }
        public string Number_WorkShop { get; set; }
    
        public virtual Type_Product Type_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Production> Production { get; set; }
    }
}
