//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuckApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Book
    {
        public int Id { get; set; }
        public Nullable<int> Id_User { get; set; }
        public Nullable<int> Id_Book { get; set; }
        public Nullable<int> Id_Status { get; set; }
        public Nullable<float> Rating { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
